# Generated by Django 2.0.5 on 2020-05-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='brg',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='development',
            name='codeReview',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='coding',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='deployment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='peerTesting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='toDO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='unitTesting',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
