export const AUTH_LOGIN_INIT = "AUTH_LOGIN_INIT";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SEND_NEW_POST_TO_SERVER_INIT = "SEND_NEW_POST_TO_SERVER_INIT";
export const SEND_NEW_POST_TO_SERVER_SUCCESS =
    "SEND_NEW_POST_TO_SERVER_SUCCESS";
export const SEND_NEW_POST_TO_SERVER_FAIL = "SEND_NEW_POST_TO_SERVER_FAIL";

export const LIST_POSTS_TO_USER_DASHBOARD_INIT =
    "LIST_POSTS_TO_USER_DASHBOARD_INIT";
export const LIST_POSTS_TO_USER_DASHBOARD_SUCCESS =
    "LIST_POSTS_TO_USER_DASHBOARD_SUCCESS";
export const LIST_POSTS_TO_USER_DASHBOARD_FAIL =
    "LIST_POSTS_TO_USER_DASHBOARD_FAIL";

export const USER_PROFILE_VIEW_INIT = "USER_PROFILE_VIEW_INIT";
export const USER_PROFILE_VIEW_SUCCESS = "USER_PROFILE_VIEW_SUCCESS";
export const USER_PROFILE_VIEW_FAIL = "USER_PROFILE_VIEW_FAIL";

export const USER_PROFILE_EDIT_INIT = "USER_PROFILE_EDIT_INIT";
export const USER_PROFILE_EDIT_SUCCESS = "USER_PROFILE_EDIT_SUCCESS";
export const USER_PROFILE_EDIT_FAIL = "USER_PROFILE_EDIT_FAIL";

export const ADMIN_USER_LIST_VIEW_INIT = "ADMIN_USER_LIST_VIEW_INIT";
export const ADMIN_USER_LIST_VIEW_SUCCESS = "ADMIN_USER_LIST_VIEW_SUCCESS";
export const ADMIN_USER_LIST_VIEW_FAIL = "ADMIN_USER_LIST_VIEW_FAIL";

export const ADMIN_CREATE_USER_INIT = "ADMIN_CREATE_USER_INIT";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_FAIL = "ADMIN_CREATE_USER_FAIL";

export const ADMIN_VIEW_ALL_POSTS_INIT = "ADMIN_VIEW_ALL_POSTS_INIT";
export const ADMIN_VIEW_ALL_POSTS_SUCCESS = "ADMIN_VIEW_ALL_POSTS_SUCCESS";
export const ADMIN_VIEW_ALL_POSTS_FAIL = "ADMIN_VIEW_ALL_POSTS_FAIL";

export const USER_POST_EDIT_INIT = "USER_POST_EDIT_INIT";
export const USER_POST_EDIT_SUCCESS = "USER_POST_EDIT_SUCCESS";
export const USER_POST_EDIT_FAIL = "USER_POST_EDIT_FAIL";

export const ADMIN_EDIT_USER_INIT = "ADMIN_EDIT_USER_INIT";
export const ADMIN_EDIT_USER_SUCCESS = "ADMIN_EDIT_USER_SUCCESS";
export const ADMIN_EDIT_USER_FAIL = "ADMIN_EDIT_USER_FAIL";

export const ADMIN_EDIT_POST_INIT = "ADMIN_EDIT_POST_INIT";
export const ADMIN_EDIT_POST_SUCCESS = "ADMIN_EDIT_POST_SUCCESS";
export const ADMIN_EDIT_POST_FAIL = "ADMIN_EDIT_POST_FAIL";

export const CREATE_COMMENT_INIT = "CREATE_COMMENT_INIT";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

export const ADMIN_COMMENT_LIST_LOAD_INIT = "ADMIN_COMMENT_LIST_LOAD_INIT";
export const ADMIN_COMMENT_LIST_LOAD_SUCCESS =
    "ADMIN_COMMENT_LIST_LOAD_SUCCESS";
export const ADMIN_COMMENT_LIST_LOAD_FAIL = "ADMIN_COMMENT_LIST_LOAD_FAIL";

export const ADMIN_COMMENT_EDIT_INIT = "ADMIN_COMMENT_EDIT_INIT";
export const ADMIN_COMMENT_EDIT_SUCCESS = "ADMIN_COMMENT_EDIT_SUCCESS";
export const ADMIN_COMMENT_EDIT_FAIL = "ADMIN_COMMENT_EDIT_FAIL";

export const USER_REGISTRATION_INIT = "USER_REGISTRATION_INIT";
export const USER_REGISTRATION_SUCCESS = "USER_REGISTRATION_SUCCESS";
export const USER_REGISTRATION_FAIL = "USER_REGISTRATION_FAIL";

//Updated
export const SEND_NEW_PROJECT_TO_SERVER_INIT      = "SEND_NEW_PROJECT_TO_SERVER_INIT";
export const SEND_NEW_PROJECT_TO_SERVER_SUCCESS   = "SEND_NEW_PROJECT_TO_SERVER_SUCCESS";
export const SEND_NEW_PROJECT_TO_SERVER_FAIL      = "SEND_NEW_PROJECT_TO_SERVER_FAIL";

export const LIST_PROJECTS_TO_USER_DASHBOARD_INIT     = "LIST_PROJECTS_TO_USER_DASHBOARD_INIT";
export const LIST_PROJECTS_TO_USER_DASHBOARD_SUCCESS  = "LIST_PROJECTS_TO_USER_DASHBOARD_SUCCESS";
export const LIST_PROJECTS_TO_USER_DASHBOARD_FAIL     = "LIST_PROJECTS_TO_USER_DASHBOARD_FAIL";

export const ADMIN_VIEW_ALL_PROJECTS_INIT     = "ADMIN_VIEW_ALL_PROJECTS_INIT";
export const ADMIN_VIEW_ALL_PROJECTS_SUCCESS  = "ADMIN_VIEW_ALL_PROJECTS_SUCCESS";
export const ADMIN_VIEW_ALL_PROJECTS_FAIL     = "ADMIN_VIEW_ALL_PROJECTS_FAIL";

export const USER_PROJECT_EDIT_INIT           = "USER_PROJECT_EDIT_INIT";
export const USER_PROJECT_EDIT_SUCCESS        = "USER_PROJECT_EDIT_SUCCESS";
export const USER_PROJECT_EDIT_FAIL           = "USER_PROJECT_EDIT_FAIL";

export const ADMIN_EDIT_PROJECT_INIT          = "ADMIN_EDIT_PROJECT_INIT";
export const ADMIN_EDIT_PROJECT_SUCCESS       = "ADMIN_EDIT_PROJECT_SUCCESS";
export const ADMIN_EDIT_PROJECT_FAIL          = "ADMIN_EDIT_PROJECT_FAIL";

export const CREATE_TASK_INIT                 = "CREATE_TASK_INIT";
export const CREATE_TASK_SUCCESS              = "CREATE_TASK_SUCCESS";
export const CREATE_TASK_FAIL                 = "CREATE_TASK_FAIL";

export const ADMIN_TASK_LIST_LOAD_INIT        = "ADMIN_TASK_LIST_LOAD_INIT";
export const ADMIN_TASK_LIST_LOAD_SUCCESS     = "ADMIN_TASK_LIST_LOAD_SUCCESS";
export const ADMIN_TASK_LIST_LOAD_FAIL        = "ADMIN_TASK_LIST_LOAD_FAIL";

export const ADMIN_TASK_EDIT_INIT             = "ADMIN_TASK_EDIT_INIT";
export const ADMIN_TASK_EDIT_SUCCESS          = "ADMIN_TASK_EDIT_SUCCESS";
export const ADMIN_TASK_EDIT_FAIL             = "ADMIN_TASK_EDIT_FAIL";

// Deliverable
export const CREATE_DELIVERABLE_INIT                 = "CREATE_DELIVERABLE_INIT";
export const CREATE_DELIVERABLE_SUCCESS              = "CREATE_DELIVERABLE_SUCCESS";
export const CREATE_DELIVERABLE_FAIL                 = "CREATE_DELIVERABLE_FAIL";

export const ADMIN_DELIVERABLE_LIST_LOAD_INIT        = "ADMIN_DELIVERABLE_LIST_LOAD_INIT";
export const ADMIN_DELIVERABLE_LIST_LOAD_SUCCESS     = "ADMIN_DELIVERABLE_LIST_LOAD_SUCCESS";
export const ADMIN_DELIVERABLE_LIST_LOAD_FAIL        = "ADMIN_DELIVERABLE_LIST_LOAD_FAIL";

export const ADMIN_DELIVERABLE_EDIT_INIT             = "ADMIN_DELIVERABLE_EDIT_INIT";
export const ADMIN_DELIVERABLE_EDIT_SUCCESS          = "ADMIN_DELIVERABLE_EDIT_SUCCESS";
export const ADMIN_DELIVERABLE_EDIT_FAIL             = "ADMIN_DELIVERABLE_EDIT_FAIL";

// Risk
export const CREATE_RISK_INIT                 = "CREATE_RISK_INIT";
export const CREATE_RISK_SUCCESS              = "CREATE_RISK_SUCCESS";
export const CREATE_RISK_FAIL                 = "CREATE_RISK_FAIL";

export const ADMIN_RISK_LIST_LOAD_INIT        = "ADMIN_RISK_LIST_LOAD_INIT";
export const ADMIN_RISK_LIST_LOAD_SUCCESS     = "ADMIN_RISK_LIST_LOAD_SUCCESS";
export const ADMIN_RISK_LIST_LOAD_FAIL        = "ADMIN_RISK_LIST_LOAD_FAIL";

export const ADMIN_RISK_EDIT_INIT             = "ADMIN_RISK_EDIT_INIT";
export const ADMIN_RISK_EDIT_SUCCESS          = "ADMIN_RISK_EDIT_SUCCESS";
export const ADMIN_RISK_EDIT_FAIL             = "ADMIN_RISK_EDIT_FAIL";

// Action
export const CREATE_ACTION_INIT                 = "CREATE_ACTION_INIT";
export const CREATE_ACTION_SUCCESS              = "CREATE_ACTION_SUCCESS";
export const CREATE_ACTION_FAIL                 = "CREATE_ACTION_FAIL";

export const ADMIN_ACTION_LIST_LOAD_INIT        = "ADMIN_ACTION_LIST_LOAD_INIT";
export const ADMIN_ACTION_LIST_LOAD_SUCCESS     = "ADMIN_ACTION_LIST_LOAD_SUCCESS";
export const ADMIN_ACTION_LIST_LOAD_FAIL        = "ADMIN_ACTION_LIST_LOAD_FAIL";

export const ADMIN_ACTION_EDIT_INIT             = "ADMIN_ACTION_EDIT_INIT";
export const ADMIN_ACTION_EDIT_SUCCESS          = "ADMIN_ACTION_EDIT_SUCCESS";
export const ADMIN_ACTION_EDIT_FAIL             = "ADMIN_ACTION_EDIT_FAIL";

// Issue
export const CREATE_ISSUE_INIT                 = "CREATE_ISSUE_INIT";
export const CREATE_ISSUE_SUCCESS              = "CREATE_ISSUE_SUCCESS";
export const CREATE_ISSUE_FAIL                 = "CREATE_ISSUE_FAIL";

export const ADMIN_ISSUE_LIST_LOAD_INIT        = "ADMIN_ISSUE_LIST_LOAD_INIT";
export const ADMIN_ISSUE_LIST_LOAD_SUCCESS     = "ADMIN_ISSUE_LIST_LOAD_SUCCESS";
export const ADMIN_ISSUE_LIST_LOAD_FAIL        = "ADMIN_ISSUE_LIST_LOAD_FAIL";

export const ADMIN_ISSUE_EDIT_INIT             = "ADMIN_ISSUE_EDIT_INIT";
export const ADMIN_ISSUE_EDIT_SUCCESS          = "ADMIN_ISSUE_EDIT_SUCCESS";
export const ADMIN_ISSUE_EDIT_FAIL             = "ADMIN_ISSUE_EDIT_FAIL";
