# Generated by Django 2.0.5 on 2020-05-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='clientManager',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
