# Generated by Django 2.0.5 on 2020-05-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='deliveredDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
