# Generated by Django 2.0.5 on 2020-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('is_displayed', models.BooleanField(default=True)),
                ('published_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
