# Generated by Django 2.0.5 on 2020-04-23 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverableName', models.CharField(max_length=100)),
                ('deliverableBody', models.TextField()),
                ('planDate', models.DateTimeField()),
                ('reviseDate', models.DateTimeField()),
                ('comments', models.CharField(max_length=100)),
                ('statusRAG', models.CharField(choices=[('Red', 'Red'), ('Amber', 'Amber'), ('Green', 'Green')], max_length=10)),
                ('is_displayed', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', related_query_name='deliverable', to='project.Project')),
            ],
        ),
    ]
