# Generated by Django 2.0.5 on 2020-04-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskName', models.CharField(max_length=100)),
                ('riskBody', models.TextField()),
                ('phaseDetected', models.CharField(max_length=50)),
                ('impact', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('probability', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('prjectPhase', models.CharField(max_length=50)),
                ('mitigation', models.TextField()),
                ('impactDate', models.DateTimeField()),
                ('is_displayed', models.BooleanField(default=True)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', related_query_name='risk', to='project.Project')),
            ],
        ),
    ]
