# Generated by Django 2.0.5 on 2020-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='riskID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='riskScore',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
