# Generated by Django 2.0.5 on 2020-05-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_auto_20200514_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='impactDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='risk',
            name='riskID',
            field=models.CharField(default='R001', max_length=20),
        ),
        migrations.AlterField(
            model_name='risk',
            name='riskScore',
            field=models.IntegerField(),
        ),
    ]
